Add changes

diff --git a/_recipes/edoapra/nwchem-singularity/nwchem-dev.mpich3/Singularity b/_recipes/edoapra/nwchem-singularity/nwchem-dev.mpich3/Singularity
--- a/_recipes/edoapra/nwchem-singularity/nwchem-dev.mpich3/Singularity
+++ b/_recipes/edoapra/nwchem-singularity/nwchem-dev.mpich3/Singularity
@@ -148,15 +148,36 @@ $FC -v \
    export mpich_options='$mpich_options --with-ucx=$MPICH_DIR' ; \
  if [ ! -f $MPICH_DIR/bin/ucx_info ]; then echo ucx_info\ not\ found ; exit 1 ; fi ;\
 elif [[ ${OFI} == builtin ]]; then echo 'builtin OFI - nothing to download'; \
-else wget --progress=dot:giga  https://github.com/ofiwg/libfabric/releases/download/v'$OFI'/libfabric-'$OFI'.tar.bz2 -O - | tar --no-same-owner  -xjf - ; \
+  else if [[ ${OFI} == git ]]; then  git clone https://github.com/ofiwg/libfabric libfabric-git && cd libfabric-git && sh autogen.sh;\
+   apt-get install -y libconfig-dev libsensors-dev libuv1-dev libfuse-dev libyaml-dev libjson-c-dev libcurl4-openssl-dev  ;\
+   cd / ; ls -lrta  ;\
+   mkdir -p $MPICH_DIR  ;\
+   cd $MPICH_DIR ; \
+   git clone https://github.com/HewlettPackard/shs-cassini-headers ;\
+   git clone https://github.com/HewlettPackard/shs-cxi-driver ;\
+   rm -rf shs*/.git ;\ 
+   cd / ; \
+   git clone https://github.com/HewlettPackard/shs-libcxi ; \
+   cd shs-libcxi ; \
+   sh autogen.sh ; \
+   ./configure --prefix=$MPICH_DIR ;\
+   make CFLAGS='-I$MPICH_DIR/shs-cassini-headers/include/ -I$MPICH_DIR/shs-cxi-driver/include/' pkg_CFLAGS=-Wall -i  ;\
+   make CFLAGS='-I$MPICH_DIR/shs-cassini-headers/include/ -I$MPICH_DIR/shs-cxi-driver/include/' install-dist_cxi_yamlDATA install-man install-pkgconfigDATA install-pkgincludeHEADERS  install-exec   ;\
+   export libfabric_options=' --enable-cxi=$MPICH_DIR  --with-cassini-headers=$MPICH_DIR/shs-cassini-headers --with-cxi-uapi-headers=$MPICH_DIR/shs-cxi-driver '; \
+ echo 'libfabric_options are' \$libfabric_options ; \
+ rm -rf shs-* ; \
+ cd / ; echo 'pwd ' $(pwd) ;ls -lrta ; \
+else wget --progress=dot:giga  https://github.com/ofiwg/libfabric/releases/download/v'$OFI'/libfabric-'$OFI'.tar.bz2 -O - | tar --no-same-owner  -xjf - ; export libfabric_options=' '; fi ;\
   cd libfabric-'$OFI' ;\
  mkdir build && cd build ; \
- ../configure --prefix=$MPICH_DIR  ;\
+ ../configure --prefix=$MPICH_DIR \$libfabric_options ;\
  make -j4 && make install ; \
  export mpich_options='$mpich_options --with-libfabric=$MPICH_DIR' ; \
+ echo 'mpich_options are \$mpich_options' ;\
 if [ ! -f $MPICH_DIR/bin/fi_info ]; then echo fi_info\ not\ found ; exit 1 ; fi \
    fi  \
 && cd .. \
+&& rm -rf libfabr* \
 && echo ' mpich_options is set to' \$mpich_options \
 && wget  --progress=dot:giga https://www.mpich.org/static/downloads/$MPICH/mpich-'$MPICH'.tar.gz  -O - | tar xzf -   \
 && cd $mpich_prefix                                                        && \
@@ -240,7 +261,7 @@ echo 'ls ~/' `ls -lrt ~/` \
 && mpif90 -show \
 && echo FC is $FC \
 && $FC -v \
-&& make GA_DEV=1 GA_BRANCH=hostid GA_URL=https://github.com/edoapra/ga.git FC=$FC -j6 || { echo 'Compilation Failure'; exit 1; } \
+&& make GA_DEV=1 GA_BRANCH=develop GA_URL=https://github.com/GlobalArrays/ga.git FC=$FC -j6 || { echo 'Compilation Failure'; exit 1; } \
 && FC=$FC ../contrib/getmem.nwchem 2000   \
 && make FC=$FC install INSTALL_PREFIX=/opt/nwchem \
 && ldd  ../bin/LINUX64/nwchem  "\
